title:              Anurag Aribandi
email:              anurag.aribandi@gmail.com
description:        Undergraduate Computer Science and HCI Researcher
author:             Anurag Aribandi

# Social Profiles
twitter_username:   
github_username:    anurag-src
facebook_username:  
instagram_username:  
linkedin_username:  anurag-aribandi-5628a51b1

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
